### ISSUE TITLE
paired read

### ISSUE THREAD

**Issue by zzz2010** [rcavalcante/mint#25]
Mint seems very awesome.  May I know how to use it for pair-end read WGBS data?

Thanks a lot
Z

**Comment by rcavalcante** [comment]
Hello,

Thanks for your interest in `mint`. In it's current state, it doesn't ... easily ... handle pair-end WGBS data. But I'm working on transitioning from `make` to `snakemake`, and I plan to add pair-end support. Unfortunately I can't really give you a timeline other than a couple months.

Thanks,
Raymond
