### ISSUE TITLE
Data sample type

### ISSUE THREAD

**Issue by yifeisun03** [rcavalcante/mint#26]
Hi:

Our lab currently got back some whole-genome bisulfite sequencing data and I've been testing with the pipeline. Our run was paired-end 150 bp. I've noticed in your test data set, only 1 fastq file per sample. Are those single end only or I can only use read1 for the pipeline?

When I configure the run with init.R, I've noticed that if I have sample_1.fastq.gz, and sample_2.fastq.gz in my data folder, the soft link it generated in the project/data folder still have the _1 and _2 in there, but when I run the pipeline with make bisulfite align, the sample_mc_hmc_bisulfite.fastq.gz file in the project/bisulfite/raw-fastq folder loses _1 and _2 and seems to have trouble link to the data/raw-fastq folder. 

Is there anything I can do to config the run to fit PE reads data?

Thank you!

**Comment by yifeisun03** [comment]
Sorry, I noticed this question was raised two years ago, and you were saying there might be some updates for the PE version. I have not seen any new activity since that date, is there anything feasible I can modify to accommodate the PE run? Thanks!

**Comment by rcavalcante** [comment]
Hello,

You're correct, when mint was originally implemented and released, it was designed for single-end reads only. Unfortunately my current working situation doesn't give me much time to support mint.  So I don't foresee implementing paired-end for this particular pipeline in the near future. I would encourage you to fork the pipeline and add any functionality as needed, if you think it's a good base to work from.

Thanks,
Raymond

**Comment by yifeisun03** [comment]
Thank you for letting me know, I'll try what I can.

Thanks,
Yifei
